# Every regulatory change detected by the scraper is stored here, along with metadata like:

import uuid
from datetime import datetime, date
from sqlalchemy import String, DateTime, Date, Text, JSON, func, Index
from sqlalchemy.orm import Mapped, mapped_column
from app.models.base import Base

class Change(Base):
    __tablename__ = "changes"
    
    # primary key : chg_xxxxxxxx
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: f"chg_{uuid.uuid4().hex[:20]}"
    )
    
    #--------Where it came from------------
    
    jurisdiction: Mapped[str] = mapped_column(
        String(10),
        nullable=False,
        index=True
    )
    
    industry: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True
    )
    
    topic: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True
    )
    
    # Source Information
    
    # name of the regulatory authority
    source_authority: Mapped[str] = mapped_column(String(200), nullable=False)
    
    # URL of the official document or announcement
    source_url: Mapped[str] = mapped_column(String(1000), nullable=False)
    
    # Snapshot of the source content at detection time (raw HTML or text)
    # Used for diffing against future snapshots
    source_snapshot: Mapped[str | None] = mapped_column(Text, nullable=True)
    
    # SHA-256 hash of the source content
    # We compare this hash on every scrape — if it changes, we process it
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    
    # Timestamp when this source was archived
    archived_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    
    #------AI generated---------
    
    # Plain-language summary generated by Claude API
    # 3–5 sentences, suitable for showing directly to end users
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    
    # Severity level — set by Claude based on scope and penalty clauses
    # Values: "critical", "major", "minor"
    severity: Mapped[str | None] = mapped_column(String(20), nullable=True, index=True)
    
    # Structured diff — machine-readable before/after of what changed
    # JSON structure: { "added": [...], "removed": [...], "modified": [...] }
    # Each item: { "clause": "Section 4.2", "text": "...", "old_text": "..." }
    diff: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    
    #--------Dates----------------
    
    # When this regulation change takes effect (from the document)
    effective_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    
    # ── Processing state ──────────────────────────
 
    # Tracks where this change is in the processing pipeline
    # "raw"        → scraped but not yet processed by AI
    # "processing" → currently being summarised by Claude
    # "ready"      → has summary + severity, ready for webhook delivery
    # "failed"     → AI processing failed (will retry)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="raw", index=True
    )
    
    # How many times AI processing has been attempted (for retry logic)
    processing_attempts: Mapped[int] = mapped_column(
        nullable=False, default=0
    )
    
    # Error message if processing failed
    processing_error: Mapped[str | None] = mapped_column(Text, nullable=True)
 
    # Timestamps
    detected_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    processed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    
    # ── Database indexes ──────────────────────────
    __table_args__ = (
        # Composite index for the most common query:
        # "give me all changes for India + fintech"
        Index("ix_changes_jurisdiction_industry", "jurisdiction", "industry"),
        # Index for status-based queries (worker polls for "raw" records)
        Index("ix_changes_status_detected", "status", "detected_at"),
    )
 
    def __repr__(self) -> str:
        return (
            f"<Change {self.id} "
            f"{self.jurisdiction}/{self.industry} "
            f"severity={self.severity} "
            f"status={self.status}>"
        )